2025-04-18 20:20:00,093 ERROR scheduler Exception in Enqueue Events for Site erpnext.localhost
Traceback (most recent call last):
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 117, in enqueue_events_for_site
    if is_scheduler_inactive():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 161, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 174, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/database/database.py", line 884, in get_single_value
    ).run()
      ^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 80, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/database/database.py", line 237, in sql
    self.connect()
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/database/database.py", line 135, in connect
    self.get_connection()
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 105, in get_connection
    conn = self._get_connection()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 111, in _get_connection
    return self.create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/ninaanic/Tehnicke/12_semestar/diplomski/frappe_docker/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_5c89b2c0940c61ec'@'localhost' (using password: YES)")
